const products = [
  { id:'vessel', name:'Mori Vessel', category:'lifestyle', label:'Lifestyle', price:189000, rating:'★★★★★', image:'assets/images/product-vessel.svg', description:'Vas keramik bertekstur dengan siluet lembut untuk sudut ruang yang membutuhkan sedikit ketenangan.', badge:'New', sort:'latest' },
  { id:'tote', name:'Daily Carry Tote', category:'accessories', label:'Accessories', price:249000, rating:'★★★★★', image:'assets/images/product-tote.svg', description:'Tas kanvas ringan dengan ruang yang cukup untuk hari yang panjang dan saku dalam untuk barang kecil.', badge:'Popular', sort:'popular' },
  { id:'lamp', name:'Halo Desk Lamp', category:'workspace', label:'Workspace', price:329000, rating:'★★★★☆', image:'assets/images/product-lamp.svg', description:'Lampu meja dengan cahaya hangat dan bentuk ringkas. Teman yang baik untuk fokus setelah matahari turun.', badge:'New', sort:'latest' },
  { id:'notebook', name:'Field Notes Set', category:'workspace', label:'Workspace', price:79000, rating:'★★★★★', image:'assets/images/product-notebook.svg', description:'Set tiga notebook untuk ide, daftar, dan hal-hal kecil yang ingin kamu ingat.', badge:'', sort:'popular' },
  { id:'mug', name:'Sunday Mug', category:'lifestyle', label:'Lifestyle', price:119000, rating:'★★★★☆', image:'assets/images/product-mug.svg', description:'Cangkir stoneware dengan pegangan nyaman untuk ritual minum yang lebih pelan.', badge:'', sort:'popular' },
  { id:'pouch', name:'Soft Utility Pouch', category:'accessories', label:'Accessories', price:99000, rating:'★★★★★', image:'assets/images/product-pouch.svg', description:'Pouch serbaguna berbahan ripstop untuk kabel, kosmetik, atau rahasia kecil sehari-hari.', badge:'', sort:'latest' },
  { id:'tray', name:'Arc Catchall Tray', category:'lifestyle', label:'Lifestyle', price:149000, rating:'★★★★☆', image:'assets/images/product-tray.svg', description:'Nampan kecil untuk kunci, perhiasan, dan benda yang biasanya menghilang di pagi hari.', badge:'', sort:'popular' },
  { id:'stand', name:'Fold Phone Stand', category:'workspace', label:'Workspace', price:89000, rating:'★★★★☆', image:'assets/images/product-stand.svg', description:'Phone stand lipat yang membuat meja terasa lebih rapi dan panggilan lebih nyaman.', badge:'', sort:'latest' }
];
const rupiah = (value) => `Rp ${value.toLocaleString('id-ID')}`;
const grid = document.querySelector('#product-grid');
const emptyState = document.querySelector('#empty-state');
const searchInput = document.querySelector('#product-search');
let activeFilter = 'all';
let cart = JSON.parse(localStorage.getItem('naya-demo-cart') || '[]');
let activeProduct = null;
let modalQuantity = 1;

function productCard(product, index) {
  return `<article class="product-card" style="animation-delay:${index * 45}ms"><div class="product-image">${product.badge ? `<span class="product-badge">${product.badge}</span>` : ''}<img src="${product.image}" alt="${product.name}" loading="lazy"><button class="quick-add" data-add="${product.id}" aria-label="Tambah ${product.name} ke cart">+</button></div><div class="product-info"><div class="product-meta"><span>${product.label}</span><span>${product.rating}</span></div><h3>${product.name}</h3><div class="product-bottom"><strong class="product-price">${rupiah(product.price)}</strong><button class="view-button" data-view="${product.id}">Lihat detail</button></div></div></article>`;
}
function getVisibleProducts() {
  const query = searchInput.value.trim().toLowerCase();
  let list = products.filter((product) => `${product.name} ${product.label}`.toLowerCase().includes(query));
  if (activeFilter === 'latest' || activeFilter === 'popular') list = list.filter((product) => product.sort === activeFilter);
  if (['lifestyle', 'accessories', 'workspace'].includes(activeFilter)) list = list.filter((product) => product.category === activeFilter);
  if (activeFilter === 'low') list.sort((a, b) => a.price - b.price);
  if (activeFilter === 'high') list.sort((a, b) => b.price - a.price);
  return list;
}
function renderProducts() { const list = getVisibleProducts(); grid.innerHTML = list.map(productCard).join(''); emptyState.hidden = list.length > 0; }
function saveCart() { localStorage.setItem('naya-demo-cart', JSON.stringify(cart)); renderCart(); }
function addToCart(id, quantity = 1) { const existing = cart.find((item) => item.id === id); if (existing) existing.quantity += quantity; else cart.push({ id, quantity }); saveCart(); openCart(); }
function changeQuantity(id, amount) { const item = cart.find((entry) => entry.id === id); if (!item) return; item.quantity += amount; cart = cart.filter((entry) => entry.quantity > 0); saveCart(); }
function renderCart() { const items = document.querySelector('#cart-items'); const total = cart.reduce((sum, item) => { const product = products.find((entry) => entry.id === item.id); return sum + (product ? product.price * item.quantity : 0); }, 0); document.querySelector('#cart-count').textContent = cart.reduce((sum, item) => sum + item.quantity, 0); document.querySelector('#cart-label').textContent = `(${cart.reduce((sum, item) => sum + item.quantity, 0)})`; document.querySelector('#cart-total').textContent = rupiah(total); items.innerHTML = cart.length ? cart.map((item) => { const product = products.find((entry) => entry.id === item.id); return `<div class="cart-item"><img src="${product.image}" alt="${product.name}"><div><h3>${product.name}</h3><p>${rupiah(product.price)}</p><div class="cart-quantity"><button data-cart-change="-" data-id="${product.id}">-</button><span>${item.quantity}</span><button data-cart-change="+" data-id="${product.id}">+</button></div></div><button class="remove-item" data-remove="${product.id}">Remove</button></div>`; }).join('') : '<p class="cart-empty">Cart kamu masih kosong. Temukan sesuatu yang terasa pas.</p>'; }
function openCart() { document.querySelector('#cart-drawer').classList.add('is-open'); document.querySelector('#cart-drawer').setAttribute('aria-hidden','false'); document.querySelector('.drawer-backdrop').classList.add('is-open'); document.body.classList.add('no-scroll'); }
function closeCart() { document.querySelector('#cart-drawer').classList.remove('is-open'); document.querySelector('#cart-drawer').setAttribute('aria-hidden','true'); document.querySelector('.drawer-backdrop').classList.remove('is-open'); document.body.classList.remove('no-scroll'); }
function openModal(id) { activeProduct = products.find((product) => product.id === id); modalQuantity = 1; document.querySelector('#modal-image').src = activeProduct.image; document.querySelector('#modal-image').alt = activeProduct.name; document.querySelector('#modal-category').textContent = activeProduct.label; document.querySelector('#modal-name').textContent = activeProduct.name; document.querySelector('#modal-rating').textContent = activeProduct.rating; document.querySelector('#modal-price').textContent = rupiah(activeProduct.price); document.querySelector('#modal-description').textContent = activeProduct.description; document.querySelector('#modal-quantity').textContent = modalQuantity; document.querySelector('#product-modal').showModal(); }
const modal = document.querySelector('#product-modal');
document.addEventListener('click', (event) => { const add = event.target.closest('[data-add]'); const view = event.target.closest('[data-view]'); const category = event.target.closest('[data-category-filter]'); const cartChange = event.target.closest('[data-cart-change]'); const remove = event.target.closest('[data-remove]'); if (add) addToCart(add.dataset.add); if (view) openModal(view.dataset.view); if (category) { activeFilter = category.dataset.categoryFilter; document.querySelectorAll('.filter-tabs button').forEach((button) => button.classList.remove('active')); searchInput.value = ''; renderProducts(); document.querySelector('#products').scrollIntoView({ behavior:'smooth' }); } if (cartChange) changeQuantity(cartChange.dataset.id, cartChange.dataset.cartChange === '+' ? 1 : -1); if (remove) { cart = cart.filter((item) => item.id !== remove.dataset.remove); saveCart(); } });
document.querySelectorAll('.filter-tabs button').forEach((button) => button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('.filter-tabs button').forEach((item) => item.classList.toggle('active', item === button)); renderProducts(); }));
searchInput.addEventListener('input', renderProducts);
document.querySelector('.cart-trigger').addEventListener('click', openCart); document.querySelectorAll('[data-close-cart]').forEach((element) => element.addEventListener('click', closeCart));
document.querySelector('.modal-close').addEventListener('click', () => modal.close()); document.querySelector('#modal-add').addEventListener('click', () => { addToCart(activeProduct.id, modalQuantity); modal.close(); });
document.querySelectorAll('[data-modal-quantity]').forEach((button) => button.addEventListener('click', () => { modalQuantity = Math.max(1, modalQuantity + (button.dataset.modalQuantity === '+' ? 1 : -1)); document.querySelector('#modal-quantity').textContent = modalQuantity; }));
document.querySelector('#checkout-button').addEventListener('click', () => window.alert('Checkout demo berhasil dibuka. Pembayaran belum terhubung karena ini demo portfolio Shark Studio.'));
document.querySelector('#newsletter-form').addEventListener('submit', (event) => { event.preventDefault(); document.querySelector('#form-message').textContent = 'Berhasil subscribe - ini masih demo.'; event.target.reset(); });
const menuToggle = document.querySelector('.menu-toggle'); const nav = document.querySelector('#site-nav'); menuToggle.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', open); document.body.classList.toggle('no-scroll', open); }); document.querySelectorAll('.site-nav a').forEach((link) => link.addEventListener('click', () => { nav.classList.remove('open'); menuToggle.setAttribute('aria-expanded','false'); document.body.classList.remove('no-scroll'); })); document.querySelector('[data-scroll-search]').addEventListener('click', () => { document.querySelector('#products').scrollIntoView({ behavior:'smooth' }); window.setTimeout(() => searchInput.focus(), 500); });
const revealObserver = new IntersectionObserver((entries, observer) => { entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }); }, { threshold:.12 }); document.querySelectorAll('.reveal-item').forEach((item) => revealObserver.observe(item));
const hideLoading = () => document.querySelector('#loading-screen').classList.add('is-hidden'); window.addEventListener('load', () => window.setTimeout(hideLoading, 300)); window.setTimeout(hideLoading, 900); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') { closeCart(); if (modal.open) modal.close(); } }); renderProducts(); renderCart();